import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { GoogleOAuthProvider } from "@react-oauth/google";  // <<< Importa aqui

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ManAI - te devolve para o jogo",
  description: "Generated by FinHero",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleOAuthProvider clientId="925023549535-l920h8gn0ksmoquh17jrfjt16a2g34ek.apps.googleusercontent.com">  {/* <<< Aqui */}
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}

